baseURL = "https://newamber.netlify.app"
languageCode = "zh-CN"
title = "藍色大門"
copyright = "newamber. 本站遵循 CC-BY-NC 4.0 协议"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[params]
  subtitle = "爱你就像爱生命"
  enableValine = true
  enableMathJax = true

[params.valine]
  appId = "mXEGFQDHRlfdKl8FUHEOg8Ek-gzGzoHsz"
  appKey = "g2SEzX0xTYF5Lbf6s7oulNX6"
  avator = "retro"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  url = "/posts"
  name = "随笔"
  weight = 1
[[menu.main]]
  url = "/technology"
  name = "技术"
  weight = 2
[[menu.main]]
  url = "/categories"
  name = "目录"
  weight = 3
[[menu.main]]
  url = "/tags"
  name = "标签"
  weight = 4
[[menu.main]]
  url = "/index.xml"
  name = "RSS"
  weight = 5